version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    entrypoint: wait-for db:3306 -t 50 -- docker-entrypoint.sh
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0.3
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
